version: '3.7'

services:
  marsel-db:
    image: mariadb:latest
    container_name: marsel-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./.docker-data/mariadb:/var/lib/mysql
      - ./scripts/database:/docker-entrypoint-initdb.d

networks:
  default:
    name: marsel-network
