marsel:
  app:
    name: Marsel
    slug: marsel
  authentication:
    jwt:
      secret: mars-machine:mars-is-there-waiting-to-be-reached
      expiration: 3600000
      refreshExpiration: 360000

spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
