spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: root
        url: jdbc:mariadb://localhost:3306/springbootdb
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
